env:
  browser: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
    indent: [error, 4]
    semi: [error, "always"]
    camelcase: off
    comma-dangle: [error, "always-multiline"]
    space-before-function-paren: [error, "never"]
    quote-props: [error, "consistent-as-needed"]
    sort-imports: [off, {
        ignoreCase: true,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
    }]
